[project]
name = "moneytalks"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "pandas>=2.3.1",
    "openpyxl>=3.1.5",
    "python-dotenv>=1.0.0"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.optional-dependencies]
dev = [
    "isort>=5.13.0",
    "pytest>=8.4.1",
    "flake8>=7.3.0",
    "mypy>=1.10.0"
]

[tool.isort]
profile = "black"
line_length = 88

[tool.black]
line_length = 88

[tool.mypy]
strict = true